##
# ansible-playbook -i inventory aap-configuration-deploy.yml
##

- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/aap-config.yml
  tasks:

    - name: Create AAP organizations
      awx.awx.organization:
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ organizations }}"
      when:
        - organizations is defined
        - organizations|length > 0

    - name: Create AAP teams
      awx.awx.team:
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        organization: "{{ item.org }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ teams }}"
      when:
        - teams is defined
        - teams|length > 0

    - name: Create AAP Users
      awx.awx.user:
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        email: "{{ item.email }}"
        update_secrets: false
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ users }}"
      when:
        - users is defined
        - users|length > 0

    - name: Add AAP Users to organization 
      awx.awx.role:
        user: "{{ item.username }}"
        role: "{{ item.role }}"
        organization: "{{ item.org }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ users }}"
      when:
        - users is defined
        - users|length > 0

    - name: Create AAP admin Users
      awx.awx.user:
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        email: "{{ item.email }}"
        update_secrets: false
        superuser: yes
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ admin_users }}"
      when:
        - admin_users is defined
        - admin_users|length > 0

    - name: Create AAP auditor Users
      awx.awx.user:
        username: "{{ item.username }}"
        password: "{{ item.password }}"
        email: "{{ item.email }}"
        update_secrets: false
        auditor: yes
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ auditor_users }}"
      when:
        - auditor_users is defined
        - auditor_users|length > 0

    - name: Create AAP Inventories
      awx.awx.inventory:
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        organization: "{{ item.org }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ inventories }}"
      when:
        - inventories is defined
        - inventories|length > 0

    - name: Create Credentials
      awx.awx.credential:
        name: "{{ item.name }}"
        organization: "{{ item.org }}"
        credential_type: "{{ item.type }}"
        update_secrets: false
        inputs:
          username: "{{ item.user }}"
          password: "{{ item.pass }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ scm_credentials }}"
      when:
        - scm_credentials is defined
        - scm_credentials|length > 0

    - name: Create SCM Projects
      awx.awx.project:
        name: "{{ item.name }}"
        description: "{{ item.desc }}"
        organization: "{{ item.org }}"
        scm_branch: "{{ item.git_branch }}"
        scm_clean: yes
        #scm_credential: "{{ item.git_cred }}"
        scm_delete_on_update: yes
        scm_type: git
        scm_update_on_launch: yes
        scm_url: "{{ item.git_url }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ scm_projects }}"
      when:
        - scm_projects is defined
        - scm_projects|length > 0

    - name: Create AAP Job Templates
      awx.awx.job_template:
        name: "{{ item.name }}"
        job_type: "run"
        organization: "{{ item.org }}"
        inventory: "{{ item.inv }}"
        project: "{{ item.project }}"
        playbook: "{{ item.playbook }}"
        credentials: "{{ item.creds }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ scm_jobtemplates }}"
      when:
        - scm_jobtemplates is defined
        - scm_jobtemplates|length > 0


    - name: Create AAP Workflow Job Templates
      awx.awx.workflow_job_template:
        name: "{{ item.name }}"
        organization: "{{ item.org }}"
        inventory: "{{ item.inv }}"
        schema: "{{ item.steps }}"
        state: present
        validate_certs: no
        controller_host: "{{ aap_host }}"
        controller_username: "{{ aap_user }}"
        controller_password: "{{ aap_pass }}"
      loop: "{{ scm_workflowjobtemplates }}"
      when:
        - scm_workflowjobtemplates is defined
        - scm_workflowjobtemplates|length > 0