aap_host: "{{ vault_aap_host }}"
aap_user: "{{ vault_aap_user }}"
aap_pass: "{{ vault_aap_pass }}"

hub_host: "{{ vault_hub_host }}"
hub_token: "{{ vault_hub_token }}"

python_interpreter: "{% raw %}{{ ansible_playbook_python }}{% endraw %}"

slack_webhook: "{{ vault_slack_webhook }}"

domain: demoday.com

organizations:
  - name: DemoDay
    desc: "DemoDay Organization"

teams: []

users:
  - username: ansibledemoday
    password: redhat
    email: ansibledemoday@gmail.com
    org: DemoDay
    role: member

admin_users: []

auditor_users: []

inventories: 
  - name: Dev
    desc: "Development Inventory"
    org: Default
  - name: "Automation Controller Inventory"
    desc: "Automation Controller Inventory"
    org: Default

hosts: 
  - name: localhost
    desc: ""
    inv: "Automation Controller Inventory"
    vars: { "ansible_connection": "local", "ansible_python_interpreter": "{% raw %}{{ python_interpreter }}{% endraw %}" }

execution_enviroment: 
  - name: ee-ansible-demoday
    desc: quay.io/demoday/ee-demoday-image:1.1
  - name: ee-notify-demoday
    desc: quay.io/demoday/ee-notify-image:1.3

scm_custom_credential_types:
  - name: "GitLab Access Token"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/gitlab_acces_token_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/gitlab_acces_token_injectors.json') }}"
  - name: "Sengrid API Key"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/sendgrid_api_key_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/sendgrid_api_key_injectors.json') }}"
  - name: "Automation Hub API Token"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/automation_hub_api_token_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/automation_hub_api_token_injectors.json') }}"
  - name: "GitLab SSH Key"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/gitlab_acces_ssh_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/gitlab_acces_ssh_injectors.json') }}"
  - name: "Slack API Webhook"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/slack_api_webhook_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/slack_api_webhook_injectors.json') }}"

scm_credentials:
  - name: "[CICD] Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: Default
    type: "Red Hat Ansible Automation Platform"
    inputs:
      host: "https://{{ aap_host }}"
      username: "{{ aap_user }}"
      password: "{{ aap_pass }}"
  - name: "[CICD] GitLab Access Token"
    desc: "GitLab Access Token"
    org: Default
    type: "GitLab Access Token"
    inputs:
      gitlab_access_token: "{{ vault_gitlab_access_token }}"
  - name: "[CICD] Sengrid API Key"
    desc: "Sengrid API Key"
    org: Default
    type: "Sengrid API Key"
    inputs:
      sendgrid_api_key: "{{ vault_sendgrid_api_key }}"
  - name: "[CICD] Automation Hub API Token"
    desc: "Automation Hub API Token"
    org: Default
    type: "Automation Hub API Token"
    inputs:
      token: "{{ hub_token }}"
      host: "{{ hub_host }}"
  - name: "[CICD] GitLab SSH Key"
    desc: "GitLab SSH Key"
    org: Default
    type: "GitLab SSH Key"
    inputs:
      gitlab_private_key: "{{ vault_gitlab_private_key }}"
  - name: "[CICD] Slack API Webhook"
    desc: "Slack API Webhook"
    org: Default
    type: "Slack API Webhook"
    inputs:
      slack_webhook: "{{ vault_slack_webhook }}"

scm_projects:
  - name: "[CICD] Ansible CI/CD"
    desc: "Ansible CI/CD Project"
    org: Default
    git_url: "https://github.com/acidonper/ansible-cicd-demo-day.git"
    git_branch: master
    git_cred: ""

scm_jobtemplates:
  - name: "[JT][CICD] Publish Collection to Automation Hub"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/02-publish-collection-hub.yml"
    creds: "[CICD] Automation Hub API Token"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Promotion DEV -> PRO"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/03-promotion.yml"
    creds: 
      - "[CICD] Automation Hub API Token"
      - "[CICD] GitLab SSH Key"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Notify Tests Reports"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/01-notify-tests-reports.yml"
    creds: "[CICD] Slack API Webhook"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Create new Pipeline from Template"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-create-cicd-pipeline.yml"
    creds: "[CICD] Red Hat Ansible Automation Platform Credential"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Create new GitLab Project"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/01-create-gitlab-proyect.yml"
    creds: "[CICD] GitLab Access Token"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Notify Onboarded Project"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/02-notify-onboarded-project.yml"
    creds: "[CICD] Sengrid API Key"
    execution_environment: "ee-notify-demoday"

scm_jobtemplates_survey:
  - name: "[JT][CICD] Sanity Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-sanity.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-sanity-test-survey.json') }}"
  - name: "[JT][CICD] Units Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-units.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-units-tests-survey.json') }}"
  - name: "[JT][CICD] Integration Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-integration.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-integration-tests-survey.json') }}"

scm_workflowjobtemplates:
  - name: "[WF][CICD] Pipeline Template - Collection Promotion"
    org: Default
    inv: Dev
    steps:
      - identifier: Sanity Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Sanity Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Units Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Units Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Integration Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Integration Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Notify Tests Reports
        all_parents_must_converge: yes
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Notify Tests Reports"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Publish Collection to Automation Hub
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: Publish Collection to Automation Hub
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Publish Collection to Automation Hub"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: "Promotion DEV -> PRO"
          failure_nodes: []
          always_nodes: []
          credentials: []      
      - identifier: "Promotion DEV -> PRO"
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Promotion DEV -> PRO"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: [] 

scm_workflowjobtemplates_survey:
  - name: "[WF][CICD] Onboarding new project"
    org: Default
    inv: "Automation Controller Inventory"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/onboarding-new-project-survey.json') }}"
    steps:
      - identifier: Create new Pipeline from Template
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new Pipeline from Template"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Create new GitLab Project
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: Create new GitLab Project
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new GitLab Project"
          type: job_template
        credentials: []
        related:
          success_nodes: 
            - identifier: Notify Onboarded Project
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Notify Onboarded Project
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Notify Onboarded Project"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []  
