aap_host: aap.apps.ocp4cluster.ocp4.cfernand.com
aap_user: admin
aap_pass: redhat

domain: demoday.com

organizations:
  - name: DemoDay
    desc: "DemoDay Organization"

teams: []

users:
  - username: ansibledemoday
    password: redhat
    email: ansibledemoday@gmail.com
    org: DemoDay
    role: member

admin_users: []

auditor_users: []

inventories: 
  - name: Dev
    desc: "Development Inventory"
    org: Default
  - name: "Automation Controller Inventory"
    desc: "Automation Controller Inventory"
    org: Default

hosts: 
  - name: localhost
    desc: ""
    inv: "Automation Controller Inventory"
    vars: { "ansible_connection": "local" }

execution_enviroment: 
  - name: ee-ansible-demoday
    desc: quay.io/demoday/ee-demoday-image:1.0

scm_custom_credential_types:
  - name: "GitLab Access Token"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/gitlab_acces_token_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/gitlab_acces_token_injectors.json') }}"
  - name: "Sengrid API Key"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/sendgrid_api_key_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/sendgrid_api_key_injectors.json') }}"

scm_credentials:
  - name: "[CICD] Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: Default
    type: "Red Hat Ansible Automation Platform"
    host: "https://{{ aap_host }}"
    user: "{{ aap_user }}"
    pass: "{{ aap_pass }}"

scm_custom_credentials:
  - name: "[CICD] GitLab Access Token"
    desc: "GitLab Access Token"
    org: Default
    type: "GitLab Access Token"
    token: "{{ vault_gitlab_access_token }}"
  - name: "[CICD] Sengrid API Key"
    desc: "Sengrid API Key"
    org: Default
    type: "Sengrid API Key"
    token: "{{ vault_sendgrid_api_key }}"

scm_projects:
  - name: "[CICD] Ansible CI/CD"
    desc: "Ansible CI/CD Project"
    org: Default
    git_url: "https://github.com/acidonper/ansible-cicd-demo-day.git"
    git_branch: master
    git_cred: ""

scm_jobtemplates:
  - name: "[JT][CICD] Publish Collection to Automation Hub"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/02-publish-collection-hub.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Promotion DEV -> PRO"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/03-promotion.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Notify Tests Reports"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/01-notify-tests-reports.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Create new Pipeline from Template"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/create_workflow_cicd.yml"
    creds: "[CICD] Red Hat Ansible Automation Platform Credential"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Create new GitLab Project"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/create_gitlab_proyect.yml"
    creds: "[CICD] GitLab Access Token"
    execution_environment: "ee-ansible-demoday"
  - name: "[JT][CICD] Notify Onboarded Project"
    org: Default
    inv: "Automation Controller Inventory"
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/notify_onboarded_project.yml"
    creds: "[CICD] Sengrid API Key"
    execution_environment: "ee-ansible-demoday"

scm_jobtemplates_survey:
  - name: "[JT][CICD] Sanity Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-sanity.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-sanity-test-survey.json') }}"
  - name: "[JT][CICD] Units Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-units.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-units-tests-survey.json') }}"
  - name: "[JT][CICD] Integration Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-integration.yml"
    creds: []
    execution_environment: "ee-ansible-demoday"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/00-integration-tests-survey.json') }}"

scm_workflowjobtemplates:
  - name: "[WF][CICD] Pipeline Template - Collection Promotion"
    org: Default
    inv: Dev
    steps:
      - identifier: Sanity Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Sanity Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Units Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Units Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Integration Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Integration Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Notify Tests Reports
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Notify Tests Reports
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Notify Tests Reports"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Publish Collection to Automation Hub
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: Publish Collection to Automation Hub
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Publish Collection to Automation Hub"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: "Promotion DEV -> PRO"
          failure_nodes: []
          always_nodes: []
          credentials: []      
      - identifier: "Promotion DEV -> PRO"
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Promotion DEV -> PRO"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: [] 

scm_workflowjobtemplates_survey:
  - name: "[WF][CICD] Onboarding new project"
    org: Default
    inv: "Automation Controller Inventory"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/onboarding-new-project-survey.json') }}"
    steps:
      - identifier: Create new Pipeline from Template
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new Pipeline from Template"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Create new GitLab Project
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: Create new GitLab Project
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new GitLab Project"
          type: job_template
        credentials: []
        related:
          success_nodes: 
            - identifier: Notify Onboarded Project
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Notify Onboarded Project
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Notify Onboarded Project"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []  
