aap_host: aap.apps.ocp4cluster.ocp4.cfernand.com
aap_user: admin
aap_pass: redhat

domain: demoday.com

organizations:
  - name: DemoDay
    desc: "DemoDay Organization"

teams: []

users:
  - username: ansibledemoday
    password: redhat
    email: ansibledemoday@gmail.com
    org: DemoDay
    role: member

admin_users: []

auditor_users: []

inventories: 
  - name: Dev
    desc: "Development Inventory"
    org: Default

hosts: 
  - name: localhost
    desc: "Local Host Group"
    org: Default
    vars: '{"ansible_connection": "local"}'

execution_enviroment: 
  - name: ansible-ee-ansible-test
    desc: quay.io/adelahoz/ansible-ee-ansible-test

scm_credential_types:
  - name: "GitLab Access Token"
    kind: cloud
    inputs: "{{ lookup('file', 'credential_types/gitlab_acces_token_inputs.json') }}"
    injectors: "{{ lookup('file', 'credential_types/gitlab_acces_token_injectors.json') }}"

scm_credentials:
  - name: "[CICD] Red Hat Ansible Automation Platform Credential"
    desc: "Red Hat Ansible Automation Platform Credential"
    org: Default
    type: "Red Hat Ansible Automation Platform"
    host: "https://{{ aap_host }}"
    user: "{{ aap_user }}"
    pass: "{{ aap_pass }}"

scm_projects:
  - name: "[CICD] Ansible CI/CD"
    desc: "Ansible CI/CD Project"
    org: Default
    git_url: "https://github.com/acidonper/ansible-cicd-demo-day.git"
    git_branch: master
    git_cred: ""

scm_jobtemplates:
  - name: "[JT][CICD] Sanity Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-sanity.yml"
    creds: []
    execution_environment: "ansible-ee-ansible-test"
    survey_enabled: yes
    survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
  - name: "[JT][CICD] Units Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-units.yml"
    creds: []
    execution_environment: "ansible-ee-ansible-test"
    survey_enabled: yes
    survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
  - name: "[JT][CICD] Integration Tests"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/00-integration.yml"
    creds: []
    execution_environment: "ansible-ee-ansible-test"
    survey_enabled: yes
    survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
  - name: "[JT][CICD] Publish Collection to Automation Hub"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/publish_collection_hub.yml"
    creds: []
    execution_environment: ""
    survey_enabled: ''
  - name: "[JT][CICD] Promotion DEV -> PRO"
    org: Default
    inv: Dev
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/02-promotion.yml"
    creds: []
    execution_environment: ""
    survey_enabled: no
    survey_enabled: ''
  - name: "[JT][CICD] Create new Pipeline from Template"
    org: Default
    inv: Demo Inventory
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/create_workflow_cicd.yml"
    creds: "[CICD] Red Hat Ansible Automation Platform Credential"
    execution_environment: ""
    survey_enabled: no
    survey_enabled: ''
  - name: "[JT][CICD] Create new GitLab Project"
    org: Default
    inv: Demo Inventory
    project: "[CICD] Ansible CI/CD"
    playbook: "ansible_tools/playbooks/create_gitlab_proyect.yml"
    creds: []
    execution_environment: ""
    survey_enabled: no
    survey_enabled: ''

scm_workflowjobtemplates:
  - name: "[WF][CICD] Pipeline Template - Collection Promotion"
    org: Default
    inv: Dev
    steps:
      - identifier: Sanity Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Sanity Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Publish Collection to Automation Hub
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Units Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Units Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Publish Collection to Automation Hub
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Integration Tests
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Integration Tests"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: Publish Collection to Automation Hub
          failure_nodes: []
          always_nodes: []
          credentials: []  
      - identifier: Publish Collection to Automation Hub
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Publish Collection to Automation Hub"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: "Promotion DEV -> PRO"
          failure_nodes: []
          always_nodes: []
          credentials: []      
      - identifier: "Promotion DEV -> PRO"
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Promotion DEV -> PRO"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: [] 

scm_workflowjobtemplates_survey:
  - name: "[WF][CICD] Onboarding new project"
    org: Default
    inv: Demo Inventory
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'survey_specs/onboarding-new-project-survey.json') }}"
    steps:
      - identifier: node101
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new Pipeline from Template"
          type: job_template
        credentials: []
        related:
          success_nodes:
            - identifier: node201
          failure_nodes: []
          always_nodes: []
          credentials: []
      - identifier: node201
        unified_job_template:
          organization:
            name: Default
          name: "[JT][CICD] Create new GitLab Project"
          type: job_template
        credentials: []
        related:
          success_nodes: []
          failure_nodes: []
          always_nodes: []
          credentials: []  
