namespace: demoday
name: reports
version: 1.0.0
readme: README.md
authors:
- Asier Cidon <acidonpe@redhat.com>
- Cesar Fernandez <cfernand@redhat.com>
- Alejandro de la Hoz <adelahoz@redhat.com>
description: This collection allows users to publish a data set in My Business Report application

license:
- GPL-2.0-or-later

license_file: ''
tags: []
dependencies: {}

repository: https://github.com/acidonper/ansible-cicd-demo-day.git
documentation: https://github.com/acidonper/ansible-cicd-demo-day/blob/master/ansible_collections/demoday/reports/README.md
homepage: https://github.com/acidonper/ansible-cicd-demo-day.git
issues: https://github.com/acidonper/ansible-cicd-demo-day/issues
