---
- name: This is a Integration testing collection
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ gitlab_repository }}'
      dest: '/tmp/ansible-collection-folder'
      version: '{{ gitlab_branch }}'

  - name: Run integration
    ansible.builtin.shell:
      cmd: ansible-test integration --start-at api_manage
      chdir: "/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}"
    ignore_errors: yes  
    register: result_integration

  - name: "Report Integration Execution"
    set_stats:
      data:
        result_integration:  "{{ result_integration }}"