---
- name: This is a Sanity testing collection
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ git_repository }}'
      dest: '/tmp/template-ansible-collection'
      version: '{{ branch_repository }}'

  - name: Run Sanity
    ansible.builtin.shell:
      cmd: ansible-test sanity --python 3.8 --local
      chdir: "/tmp/template-ansible-collection/{{ package_collection }}/{{ name_collection }}"
    ignore_errors: yes
    register: result_sanity


  - name: "Artifact URL of test results to Tower Workflows"
    set_stats:
      data:
        result_sanity:  "{{ result_sanity }}"