---
- name: This is a Sanity testing collection
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ gitlab_repository }}'
      dest: '/tmp/ansible-collection-folder'
      version: '{{ gitlab_branch }}'

  - name: Run Sanity
    ansible.builtin.shell:
      cmd: ansible-test sanity --python 3.8 --local
      chdir: "/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}"
    ignore_errors: yes
    register: result_sanity


  - name: "Report Sanity Execution"
    set_stats:
      data:
        result_sanity:  "{{ result_sanity }}"