---
- name: This is a Units testing collection
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ gitlab_repository }}'
      dest: '/tmp/ansible-collection-folder'
      version: '{{ gitlab_branch }}'

  - name: Run units
    ansible.builtin.shell:
      cmd: ansible-test units --coverage
      chdir: "/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}"
    ignore_errors: yes
    register: result_units

  - name: "Report Units Execution"
    set_stats:
      data:
        result_units:  "{{ result_units }}"

  - name: Run coverage
    ansible.builtin.shell:
      cmd: ansible-test coverage report
      chdir: "/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}"
    ignore_errors: yes
    register: result_coverage

  - name: "Report coverage Execution"
    set_stats:
      data:
        result_coverage:  "{{ result_coverage }}"