---
- name: This is a Sanity testing collection
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Git checkout
    ansible.builtin.git:
      repo: '{{ git_repository }}'
      dest: '/tmp/template-ansible-collection'
      version: '{{ branch_repository }}'

  - name: Run units
    ansible.builtin.shell:
      cmd: ansible-test units
      chdir: "/tmp/template-ansible-collection/{{ package_collection }}/{{ name_collection }}"
    ignore_errors: yes
    register: result_units

  - name: "Report Units Execution"
    set_stats:
      data:
        result_units:  "{{ result_units }}"