---
- name: This is a Units testing collection
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: false

  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: '{{ gitlab_repository }}'
        dest: '/tmp/ansible-collection-folder'
        version: '{{ gitlab_branch }}'

    - name: Read Galaxy definition file
      ansible.builtin.slurp:
        src: '/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}/galaxy.yml'
      register: collection_galaxy_file

    - name: Define the dicctionary data
      set_fact:
        galaxy_dict: "{{ collection_galaxy_file['content'] | b64decode | from_yaml }}"

    - name: "Approve Ansible Collection {{ ansible_collection }}"
      ansible.builtin.uri:
        url: "https://{{ lookup('env', 'HUB_HOST') }}/api/galaxy/v3/collections/{{ ansible_namespace }}/{{ ansible_collection }}/versions/{{ galaxy_dict.version  }}/move/staging/published/"
        method: POST
        body_format: json
        validate_certs: "{{ validate_certs }}"
        headers:
          Authorization: "Token {{ lookup('env', 'HUB_API_TOKEN') }}"
        status_code:
          - 200
          - 202
      ignore_errors: true

    - name: Create SSH directory
      ansible.builtin.file:
        path: /home/runner/.ssh
        state: directory
        owner: runner
        group: runner
        mode: '0700'
  
    - name: Create ssh key connection
      ansible.builtin.copy: 
        dest: "/home/runner/.ssh/id_rsa"
        content: "{{ lookup('env', 'GITLAB_PRIVATE_KEY') }}"
        owner: runner
        group: runner
        mode: '0600'

    - name: Git checkout SSH
      ansible.builtin.git:
        repo: "{{ gitlab_repository | regex_replace('https://', 'git@') | regex_replace('com/', 'com:') }}"
        dest: '/tmp/ansible-collection-folder-ssh'
        version: 'master'

    - name: Merge Develop Changes
      ansible.builtin.shell: 
        cmd: git merge develop
        chdir: '/tmp/ansible-collection-folder-ssh'

    - name: Push to Master
      ansible.builtin.shell: 
        cmd: git push
        chdir: '/tmp/ansible-collection-folder-ssh'
