---
- name: This is a Units testing collection
  hosts: localhost
  gather_facts: no
  vars:
    validate_certs: false

  tasks:

    - name: Git checkout
      ansible.builtin.git:
        repo: '{{ gitlab_repository }}'
        dest: '/tmp/ansible-collection-folder'
        version: '{{ gitlab_branch }}'

    - name: Read Galaxy definition file
      ansible.builtin.slurp:
        src: '/tmp/ansible-collection-folder/ansible_collections/{{ ansible_namespace }}/{{ ansible_collection }}/galaxy.yml'
      register: collection_galaxy_file

    - name: Define the dicctionary data
      set_fact:
        galaxy_dict: "{{ collection_galaxy_file['content'] | b64decode | from_yaml }}"

    - name: approve Ansible  Collection
      ansible.builtin.uri:
        url: "https://{{ lookup('env', 'HUB_HOST') }}/api/galaxy/v3/collections/{{ ansible_namespace }}/{{ ansible_collection }}/versions/{{ galaxy_dict.version  }}/move/staging/published/"
        method: POST
        body_format: json
        validate_certs: "{{ validate_certs }}"
        headers:
          Authorization: "Token {{ lookup('env', 'HUB_API_TOKEN') }}"
        status_code:
          - 200
          - 202
