---
- name: This is a hello-world example
  hosts: localhost
  tasks:

    - name: Create a new token using username/password
      ansible.controller.token:
        description: 'Token de prueba'
        scope: "write"
        state: present
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        validate_certs: false

    - name: Add project
      ansible.controller.project:
        name: "ansible-cicd-demo-day"
        description: "Project Global CICD Collection"
        organization: "Default"
        state: present
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        scm_url: https://github.com/acidonper/ansible-cicd-demo-day
        scm_type: git
        scm_branch: master
        validate_certs: false

    - name: Add EE to the controller instance
      ansible.controller.execution_environment:
        name: "ansible-ee-ansible-test"
        image: quay.io/adelahoz/ansible-ee-ansible-test
        state: present
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        validate_certs: false

    - name: Add inventory local
      ansible.controller.inventory:
        name: "local"
        description: "local inventory"
        state: present
        organization: "Default"
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        validate_certs: false
        variables:
          ansible_connection: local


    - name: Add local host
      ansible.controller.host:
        name: localhost
        description: "Local Host Group"
        inventory: "local"
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        state: present
        validate_certs: false

    - name: Create sanity collection job template
      ansible.controller.job_template:
        name: "ansible-cicd-demo-day_sanity"
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        job_type: "run"
        organization: "Default"
        inventory: "local"
        project: "ansible-cicd-demo-day"
        playbook: "ansible_tools/playbooks/00-sanity.yml"
        state: "present"
        survey_enabled: yes
        survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
        validate_certs: false

    - name: Create units collection job template
      ansible.controller.job_template:
        name: "ansible-cicd-demo-day_units"
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        job_type: "run"
        organization: "Default"
        inventory: "local"
        project: "ansible-cicd-demo-day"
        playbook: "ansible_tools/playbooks/00-units.yml"
        state: "present"
        survey_enabled: yes
        survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
        validate_certs: false

    - name: Create integration collection job template
      ansible.controller.job_template:
        name: "ansible-cicd-demo-day_integration"
        controller_host: "{{ host_automation_platform }}"
        controller_username: "{{ user_automation_platform }}"
        controller_password: "{{ password_automation_platform }}"
        job_type: "run"
        organization: "Default"
        inventory: "local"
        project: "ansible-cicd-demo-day"
        playbook: "ansible_tools/playbooks/00-integration.yml"
        state: "present"
        survey_enabled: yes
        survey_spec: '{"name":"","description":"","spec":[{"question_name":"Add collection git repository url","question_description":"Collection Git repository URL","required":true,"type":"text","variable":"gitlab_repository","min":0,"max":1024,"default":"","choices":"","formattedChoices":[{"choice":"","isDefault":false,"id":0}],"new_question":false},{"question_name":"Add collection git repository branch","question_description":"Collection Git repository branch","required":true,"type":"text","variable":"gitlab_branch","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add namespace collection","question_description":"Name of namespace collection","required":true,"type":"text","variable":"ansible_namespace","min":0,"max":1024,"default":"","choices":"","new_question":true},{"question_name":"Add name collection","question_description":"name of collection","required":true,"type":"text","variable":"ansible_collection","min":0,"max":1024,"default":"","choices":"","new_question":true}]}'
        validate_certs: false

   