---
- name: Notify Onboarded Project
  hosts: all
  gather_facts: false
  vars:
    sendgrid_from_email_address: cfernand@redhat.com

  tasks:
    - name: debug
      ansible.builtin.debug: 
        msg: "{{ lookup('env','SENGRID_API_KEY') }}"

    - name: debug
      ansible.builtin.debug: 
        msg: "{{ sendgrid_api_key}}"
 
    - name: Send Onboarded Project Information
      community.general.sendgrid:
        api_key: "{{ lookup('env','SENGRID_API_KEY') }}"
        from_address: "{{ sendgrid_from_email_address }}"
        to_addresses: "{{ gitlab_email_address }}"
        subject: "Deployment success."
        body: "The most recent Ansible deployment was successful."
        #subject: "CICD Project Information"
        #body: "The most recent Ansible deployment was successful."
        #body: "{{ lookup('template', '../templates/onboarded_project.html.j2') }}"
        #html_body: yes
      delegate_to: localhost
