---
- name: Notify Onboarded Project
  hosts: all
  gather_facts: false
  vars:
    sendgrid_from_email_address: ansibledemoday@redhat.com

  tasks:
    - name: Send Onboarded Project Information
      community.general.sendgrid:
        username: "{{ sendgrid_username }}"
        password: "{{ sendgrid_password }}"
        # api_key: "{{ sendgrid_api_key | default(omit) }}"
        from_address: "{{ sendgrid_from_email_address }}"
        to_addresses: "{{ gitlab_email_address }}"
        subject: "[CICD] Project Information - {{ gitlab_project_name }}"
        body: "{{ lookup('template', '../templates/onboarded_project.html.j2') }}"
        html_body: yes
      run_once: True
