---
- name: Notify Onboarded Project
  hosts: all
  gather_facts: false
  vars:
    sendgrid_from_email_address: ansibledemoday@redhat.com

  tasks:
    - name: debug:
      ansible.builtin.debug: 
        msg: "{{ lookup('env','SENGRID_API_KEY') }}"
 
    - name: Send Onboarded Project Information
      community.general.sendgrid:
        api_key: "{{ lookup('env','SENGRID_API_KEY') }}"
        from_address: "{{ sendgrid_from_email_address }}"
        to_addresses: "{{ gitlab_email_address }}"
        subject: "[CICD] Project Information - {{ gitlab_project_name }}"
        body: "The most recent Ansible deployment was successful."
        #body: "{{ lookup('template', '../templates/onboarded_project.html.j2') }}"
        #html_body: yes
      delegate_to: localhost
