apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: appreports 
spec: {}
---
# Source: jump-app/charts/jump-app-cicd/templates/buildconfig.yaml
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: appreports
  name: appreports-dev
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: appreports:develop
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/acidonper/ansible-cicd-demo-day.git
      ref: master
    type: Git
    contextDir: "reports_app" 
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: openshift
    type: Source
